### PR TITLE
[Places 286] The tracer can now assign an external id

### PR DESCRIPTION
**Pull request by ChrisMichaelPerezSantiago**

### CODE REVIEW

**Comment by iamdcj** [comment]
@ChrisMichaelPerezSantiago please can you attach screenshots of the UI elements you've generated, this helps me focus purely on the code, opposed to spinning-up the app to assess the rendering of any UI developlent.

Thanks

**Comment by ChrisMichaelPerezSantiago** [comment]
@iamdcj ,

I leave you some photos of the UI


**Edit External ID via RedactorTool**

- [x] Edit Button

Capture


- [x] Modal - Edit Record ID "External ID"

Capture-2

- [x] After saving the changes

Capture-3

**Comment by iamdcj** [comment]
I've reviewed, the code looks good and the UI is consistent with the rest of the application.

@ChrisMichaelPerezSantiago if outstanding changes are required based on @FacundoMalgieri's review, please include.

**Comment by AdamLeonSmith** [comment]
Hi... I think this warrants a privacy discussion... An external ID would only be used to facilitate tracking location of an individual.  What is the source of this requirement?

**Comment by FacundoMalgieri** [comment]
@AdamLeonSmith The specs are in the [ticket](https://pathcheck.atlassian.net/browse/PLACES-286) that were taken from the designs.

@ChrisMichaelPerezSantiago could you solve the conflicts so we can Squash and merge this? thanks!

**Comment by ChrisMichaelPerezSantiago** [comment]
@FacundoMalgieri  Conflict resolved.

**Comment by altoplano** [comment]
Adam -
Not sure if I'm the only source of this requirement, but certainly have argued for it.
The need is driven by the larger context around contact tracing.
During a Contact Tracing interview all kinds of other information is associated with the patient and used to coordinate their care/follow-up etc. If SafePlaces didn't tie this other record into the information it was handling, then we force the HA to make a mapping between their own HACaseID and the SafePlacesCaseID.
I would hope this only exists in the "internal" DB, agree it is a privacy leak but leaving it out would likely just move the leak to a DB we have less influence over (i.e. the HA's CRM DB).

**Pull request merged**
