### PR TITLE
[PLACES-490] UI Animations

### PR DESCRIPTION
**Pull request by iamdcj**
I've added the [React Transition Group](https://github.com/reactjs/react-transition-group) library to the application - it is the animation library I know best, but if there is a better alternative I am happy to switch before more animations are added to the solution.

**Point Editor**
Safe Places (2)

**Modals**
Safe Places (3)

### CODE REVIEW

**Comment by yonatanmk** [comment]
Do we have design input on these animations. I can't quite put my finger on it, but something about these animations seems off/weird to me.

**Comment by yonatanmk** [comment]
I think it's the modal background sliding in and the sidebar content sliding in while the sidebar itself does not.

**Comment by iamdcj** [comment]
> I think it's the modal background sliding in and the sidebar content sliding in while the sidebar itself does not.
Not sure about the modal, but happy to alter the animation.

The sidebar is a constant, but the content within the sidebar does change; I think it would be odd to slide the entire sidebar in/out each time the content changes. I added the transition to the sidebar content when the point editor moved to within the sidebar area - I wanted to make sure the user noticed the point editor coming into view.

**Comment by iamdcj** [comment]
Safe Places (4)

**Pull request merged**
