### PR TITLE
Update page_objects.py to add object for individual data entry

### PR DESCRIPTION
**Pull request by LynnGazis**
Add elements that can be used later to add the tests:
1) Add an entry
2)  Select an individual data point and edit it
3) Select an individual data point and delete it

CSS_SELECTOR values for the Individual Data Point class currently assume only one individual data point, and may need modification for the case where there is a table of multiple individual data points.

### CODE REVIEW

**Comment by AdamLeonSmith** [comment]
Not sure why these tests are failing @sherifkozman

**Comment by sherifkozman** [comment]
@LynnGazis please pull the latest updates from `dev` branch to fix the glitch in CI/CD action.

**Comment by LynnGazis** [comment]
Pulled latest code from dev to my branch. Will try again.

**Comment by LynnGazis** [comment]
Trying pull request again.

**Comment by AdamLeonSmith** [comment]
@sherifkozman still looks like a docker problem to me!

**Pull request merged**
